add news-3 page
Dufuna-CodeCamp/Niger-II-Hack1 pull request #4
Opened 2020-08-02 21:53 UTC by JoyChukwukere

2020-08-02 21:59 UTC, faithakinbobola approved these changes

2020-08-02 22:05 UTC, goke-epapa requested changes
Move file `image.png`  to the `images` folder and remove `v.png` from `image-1`.

2020-08-02 22:05 UTC, goke-epapa commented on news-3.html
> +      <img src="images-1/image.png" alt="Virus is a virus too"><br>
```suggestion
      <img src="images/image.png" alt="Virus is a virus too"><br>
```

2020-08-02 22:05 UTC, goke-epapa commented on news-3.html
> +            <th><img src="images-1/v.png"></th>
```suggestion
            <th><img src="images/v.png"></th>
```

2020-08-03 06:16 UTC, goke-epapa approved these changes

2020-08-03 10:45 UTC, merged